# Generated by Django 5.2.5 on 2025-08-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngresosExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Ingresos Extra',
            },
        ),
        migrations.CreateModel(
            name='IngresosFijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(default='Mensual', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ingresos Fijos',
            },
        ),
    ]
