# Generated by Django 5.2.5 on 2025-08-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_ingresosextra_owner_ingresosfijos_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresosextra',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_extra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingresosfijos',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_fijos', to=settings.AUTH_USER_MODEL),
        ),
    ]
