# Generated by Django 5.2.5 on 2025-09-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_alter_ingresosextra_owner_alter_ingresosfijos_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresosfijos',
            name='period',
            field=models.CharField(max_length=100),
        ),
    ]
