# Generated by Django 5.2.5 on 2025-08-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0002_egresosextra_owner_egresosfijos_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresosextra',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos_extra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='egresosfijos',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos_fijos', to=settings.AUTH_USER_MODEL),
        ),
    ]
