# Generated by Django 5.2.5 on 2025-09-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0003_alter_egresosextra_owner_alter_egresosfijos_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresosfijos',
            name='period',
            field=models.CharField(max_length=100),
        ),
    ]
