# Generated by Django 5.2.5 on 2025-08-28 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0003_ahorromovimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorromovimiento',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
